import { chromium } from 'playwright';
import { parseArgs, withServer, visit } from './lib.mjs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { mkdir, writeFile } from 'node:fs/promises';

const available=['layout','tap-targets','slop','palette','contrast','focus'];
const measure=()=>{
 const visible=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'};
 const sel=e=>e.tagName.toLowerCase()+(e.id?'#'+e.id:'')+(typeof e.className==='string'&&e.className.trim()?'.'+e.className.trim().replace(/\s+/g,'.'):'');
 const els=[...document.querySelectorAll('body,body *')].filter(visible).map(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return {sel:sel(e),bg:s.backgroundImage,backdrop:s.backdropFilter,anim:s.animationIterationCount,left:parseFloat(s.borderLeftWidth),others:[s.borderTopWidth,s.borderRightWidth,s.borderBottomWidth].map(parseFloat),role:e.getAttribute('role'),cls:typeof e.className==='string'?e.className:'',interactive:e.matches('a,button,input,select,textarea,[role=button]'),font:s.fontFamily,size:parseFloat(s.fontSize),color:s.color,background:s.backgroundColor,outline:s.outlineStyle,shadow:s.boxShadow,rect:{x:r.x,y:r.y,w:r.width,h:r.height}}});
 const images=[...document.images].filter(visible).map(e=>{const r=e.getBoundingClientRect();return {sel:sel(e),w:r.width,h:r.height,nw:e.naturalWidth,top:r.top,bottom:r.bottom,hero:e.classList.contains('hero-image')}});
 const h=document.querySelector('h1'), stop=document.querySelector('form,table');
 const focus=[...document.querySelectorAll('a,button,input,select,textarea,[role=button]')].filter(visible).map(e=>{e.blur();const s=getComputedStyle(e),before=[s.outlineStyle,s.outlineWidth,s.outlineColor,s.boxShadow,s.borderColor];e.focus({focusVisible:true,preventScroll:true});const f=getComputedStyle(e),after=[f.outlineStyle,f.outlineWidth,f.outlineColor,f.boxShadow,f.borderColor];e.blur();return {sel:sel(e),visible:before.some((x,i)=>x!==after[i])}});
 return {scroll:document.documentElement.scrollWidth-innerWidth,nav:[...document.querySelectorAll('.site-nav li')].map(e=>getComputedStyle(e).listStyleType),tops:[...document.querySelectorAll('.site-nav a')].map(e=>e.getBoundingClientRect().top),header:document.querySelector('.site-header')?.getBoundingClientRect().height||0,logo:(()=>{const r=document.querySelector('.site-header img')?.getBoundingClientRect();return r?{top:r.top,bottom:r.bottom,h:r.height}:null})(),brand:(()=>{const r=document.querySelector('.site-header .site-brand,.site-header .brand,.site-header h1')?.getBoundingClientRect();return r?{top:r.top,bottom:r.bottom}:null})(),images,intro:h&&stop?{a:h.getBoundingClientRect().bottom,b:stop.getBoundingClientRect().top}:null,cells:[...document.querySelectorAll('th,td')].map(e=>({t:e.innerText.trim(),h:e.getBoundingClientRect().height,lh:parseFloat(getComputedStyle(e).lineHeight)||parseFloat(getComputedStyle(e).fontSize)*1.2})),targets:[...document.querySelectorAll('a[href],button,input[type=submit],input[type=button],input[type=reset],select,[role=button],input[type=checkbox],input[type=radio]')].filter(visible).map(e=>{let r=e.getBoundingClientRect();if(/checkbox|radio/.test(e.type)&&e.labels?.length){const l=e.labels[0].getBoundingClientRect();if(l.width*l.height>r.width*r.height)r=l}return {sel:sel(e),w:r.width,h:r.height}}),text:document.body.innerText,els,focus,bodyFont:getComputedStyle(document.body).fontFamily,h1Font:h?getComputedStyle(h).fontFamily:'',bodySize:parseFloat(getComputedStyle(document.body).fontSize)};
};
function audit(m, checks, width, page){const out=[],add=(c,s,v)=>out.push({check:c,selector:s,value:v,page,width});
 if(checks.includes('layout')){if(m.scroll>1)add('layout','document.documentElement.scrollWidth',m.scroll);if(width===1280){m.nav.forEach((x,i)=>{if(x!=='none')add('layout',`.site-nav li:nth-child(${i+1}) list-style-type`,x)});if(m.tops.length&&Math.max(...m.tops)-Math.min(...m.tops)>4)add('layout','.site-nav a tops',m.tops.join(','));if(m.header>120)add('layout','.site-header height',m.header);if(m.logo?.h>56)add('layout','.site-header img height',m.logo.h);if(m.logo&&m.brand&&Math.abs((m.logo.top+m.logo.bottom-m.brand.top-m.brand.bottom)/2)>12)add('layout','.site-header brand/logo centres','centres differ by >12px');}for(const im of m.images){if(im.nw&&im.w>im.nw+1)add('layout',im.sel+' rendered width',`${im.w} > natural ${im.nw}`);if(width===1280&&im.h>(im.hero?440:360))add('layout',im.sel+' rendered height',im.h);if(width===1280&&!im.hero&&im.w>width/2)add('layout',im.sel+' rendered width',im.w);if(m.intro&&im.top>=m.intro.a&&im.bottom<=m.intro.b&&im.h>200)add('layout',im.sel+' intro image height',im.h);}for(const c of m.cells)if(c.t&&!/\s/.test(c.t)&&c.h>1.6*c.lh)add('layout','table cell '+c.t,`${c.h}px / ${c.lh}px line-height`);}
 if(checks.includes('tap-targets'))for(const t of m.targets)if(t.w<44||t.h<44)add('tap-targets',t.sel,`${t.w}x${t.h}px`);
 if(checks.includes('slop')){if(/\b(elevate|seamless|next-generation|supercharge|unleash|empower|revolutioni[sz]e|cutting-edge|best-in-class)\b/i.test(m.text))add('slop','visible text','banned phrase');if(/\p{Extended_Pictographic}/u.test(m.text))add('slop','visible text','emoji');for(const e of m.els){if(e.bg.includes('gradient')&&!/\.slot\.past(?:\.|$)/.test(e.sel))add('slop',e.sel+' background-image',e.bg);if(e.backdrop!=='none')add('slop',e.sel+' backdrop-filter',e.backdrop);if(e.anim==='infinite')add('slop',e.sel+' animation-iteration-count',e.anim);if(!e.interactive&&e.left>=3&&e.others.every(x=>x<2)&&!(/alert|status/.test(e.role||'')||/\b(alert|flash|error-summary)\b/.test(e.cls)))add('slop',e.sel+' border-left',`${e.left}px; others ${e.others.join('/')}`);}if(/^(Inter|system-ui|-apple-system)(?:,|$)/i.test(m.bodyFont.trim()))add('slop','body font-family',m.bodyFont);if(m.h1Font&&m.h1Font.split(',')[0].trim().replace(/["']/g,'')===m.bodyFont.split(',')[0].trim().replace(/["']/g,''))add('slop','h1 font-family',m.h1Font);if(m.bodySize<16)add('slop','body font-size',m.bodySize+'px');}
 if(checks.includes('focus'))for(const e of m.focus||[])if(!e.visible)add('focus',e.sel,'no visible focus style');
 if(checks.includes('palette')||checks.includes('contrast')){const rgb=x=>(x.match(/[\d.]+/g)||[0,0,0]).slice(0,3).map(Number),lum=a=>a.map(v=>v/255).map(v=>v<=.03928?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);const es=m.els.filter(e=>e.sel==='body'||e.sel.includes('button')).slice(0,5);if(checks.includes('contrast'))for(const e of es){const a=lum(rgb(e.color)),b=lum(rgb(e.background));if((Math.max(a,b)+.05)/(Math.min(a,b)+.05)<4.5)add('contrast',e.sel,'contrast below 4.5:1');}if(checks.includes('palette')){if(es[0]){const c=rgb(es[0].background);if(c[2]>c[0]*1.2)add('palette',es[0].sel+' background',es[0].background);}const gradient=m.els.find(e=>e.bg.includes('gradient'));if(gradient)add('palette',gradient.sel+' background-image',gradient.bg);}}
 return out;}
async function inspect(urls,checks){const b=await chromium.launch({headless:true}),out=[];try{for(const u of urls)for(const width of [1280,390]){const p=await b.newPage({viewport:{width,height:width===1280?800:844}});await p.goto(u,{waitUntil:'networkidle'});out.push(...audit(await p.evaluate(measure),checks,width,u));await p.close();}}finally{await b.close()}return out;}

const argv=process.argv.slice(2);
if(argv[0]==='--selftest'){
 await mkdir('tools/ui/fixtures',{recursive:true});
 const good='<!doctype html><style>body{font:16px Arial;color:#222;background:#fff;margin:0}.site-header{height:50px;display:flex;align-items:center}.site-header img{width:1px;height:1px}.site-brand{font:24px Georgia}h1{font:32px Georgia}.site-nav li{list-style:none}a,button{display:inline-flex;align-items:center;min-width:44px;min-height:44px}a:focus-visible,button:focus-visible{outline:2px solid #111}</style><header class="site-header"><img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="><span class="site-brand">Clinic</span></header><nav class="site-nav"><ul><li><a href="#">Home</a></li></ul></nav><h1>Clinic care</h1><button>Open</button><p>Appointments</p>';
 const bad='<!doctype html><style>body{font:12px system-ui;color:#222;background:linear-gradient(red,blue);overflow-x:scroll}.site-header{height:150px}.site-header img{width:500px;height:90px}h1{font:12px system-ui}.site-nav li{list-style:disc}.tiny{border-left:4px solid red;min-height:20px}button{width:20px;height:20px;animation:spin 1s infinite;outline:none;box-shadow:none}button:focus-visible{outline:none;box-shadow:none}.glass{backdrop-filter:blur(2px)}@keyframes spin{to{transform:rotate(1turn)}}</style><header class="site-header"><img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=">Clinic</header><nav class="site-nav"><ul><li><a href="#">Home</a></li></ul></nav><h1>Seamless care ✨</h1><button>Open</button><p class="tiny">Panel</p><p class="glass">Glass</p>';
 await writeFile('tools/ui/fixtures/good.html',good);await writeFile('tools/ui/fixtures/bad.html',bad);
 const g=await inspect([pathToFileURL(resolve('tools/ui/fixtures/good.html')).href],available),d=await inspect([pathToFileURL(resolve('tools/ui/fixtures/bad.html')).href],available);if(g.length)throw Error('good.html failed: '+JSON.stringify(g));for(const c of available)if(!d.some(x=>x.check===c))throw Error('bad.html did not fail '+c);console.log('OK');process.exit(0);
}
const checksArg=argv.find(x=>x.startsWith('--checks='));const positional=argv.find(x=>!x.startsWith('--')&&x.split(',').every(c=>available.includes(c)));const selected=checksArg?checksArg.slice(9).split(','):positional?positional.split(','):available;const opts=parseArgs(argv.filter(x=>x!==positional));const paths=opts.paths;if(!paths.length)throw Error(`usage: node tools/ui/audit.mjs [--serve] [checks] <pages|all>`);for(const c of selected)if(!available.includes(c))throw Error('Unknown check '+c);
const failures=await withServer(opts.serve,async()=>{const b=await chromium.launch({headless:true}),out=[];try{for(const path of paths){const p=await b.newPage({viewport:{width:1280,height:800}});const url=await visit(p,path);for(const width of [1280,390]){await p.setViewportSize({width,height:width===1280?800:844});out.push(...audit(await p.evaluate(measure),selected,width,path));}await p.close();}}finally{await b.close()}return out;});
if(failures.length){for(const f of failures)console.error(`${f.page} ${f.width}px ${f.selector}: ${f.value}`);const counts=Object.groupBy(failures,f=>f.page),checks=Object.groupBy(failures,f=>f.check);console.error(`FAILURES: ${failures.length}; by page: ${Object.entries(counts).map(([p,items])=>`${p}=${items.length}`).join(', ')}`);console.error(`BY CHECK: ${Object.entries(checks).map(([check,items])=>`${check}=${items.length}`).join(', ')}`);process.exitCode=1;}else console.log('OK');
