-- Issue #4 migration.
-- The cleaned adopted dump already contains every structural/content field
-- originally listed for this migration. It must therefore remain a no-op:
-- re-adding any of these columns or keys would make db_reset fail.
-- This file is intentionally idempotent and preserves existing data.
-- Issue #84: fill short seeded doctor biographies on an existing database.
-- The length guard preserves any profile text the owner has already edited.
UPDATE `doctor` SET `WriteUp` = 'Dr. Smith is a family physician who has cared for adults and children in Singapore for more than fifteen years. He focuses on preventive health, chronic disease management and practical advice that helps patients make confident decisions between visits. He takes time to understand how symptoms affect daily routines and agrees on clear next steps with each patient.\n\nAt a consultation, patients can discuss a new concern, review an ongoing condition or plan routine screening. Dr. Smith also supports families with vaccinations and follow-up after illness, coordinating further assessment when a concern needs specialist input. He aims to make each visit useful by explaining findings in plain language and setting out what to monitor at home. Patients are welcome to bring a current medication list and questions..' WHERE `User` = 'drsmith' AND CHAR_LENGTH(`WriteUp`) < 400;
UPDATE `doctor` SET `WriteUp` = 'Dr. Nair is a restorative dentist and orthodontist who takes time to explain each treatment option. Her calm, preventive approach helps nervous patients feel comfortable, while her experience with families and young adults supports healthy smiles at every stage of life. She discusses the reasons for a recommended procedure and answers questions before care begins.\n\nPatients see Dr. Nair for routine examinations, tooth or gum concerns, restorative work and orthodontic assessment. She encourages regular preventive visits and gives practical guidance on caring for teeth between appointments. When treatment involves more than one step, she explains the sequence and expected follow-up so patients can plan around work, school and family commitments. Patients can bring prior dental records or note current concerns..' WHERE `User` = 'drnair' AND CHAR_LENGTH(`WriteUp`) < 400;
UPDATE `doctor` SET `WriteUp` = 'Dr. Tan is a paediatrician who looks after newborns, school-age children and teenagers. He combines careful assessment with clear guidance for parents, and has a particular interest in childhood asthma, nutrition and supporting healthy development through the changing school years. He welcomes questions from caregivers and explains how a child’s symptoms and history inform the assessment.\n\nFamilies can book for an illness review, a growth or development check, or follow-up for an ongoing condition such as asthma. Dr. Tan discusses practical steps parents can use at home and when to seek further care. He aims to make visits comfortable for children while giving caregivers a clear account of the plan and any signs that should prompt another review. Please bring relevant health records and note any recent changes..' WHERE `User` = 'drtan' AND CHAR_LENGTH(`WriteUp`) < 400;
UPDATE `doctor` SET `WriteUp` = 'Dr. Lim treats common and complex skin conditions, including eczema, acne, pigmentation and persistent rashes. She considers an accurate diagnosis and a manageable routine equally important, so consultations include practical skin care advice that takes a patient’s daily life into account. She explains what to watch for and how each treatment option is used.\n\nPatients can book when a skin concern keeps returning, has changed or has not settled with initial care. Dr. Lim also reviews hair and nail concerns and helps patients understand when follow-up is useful. During the visit, she asks about previous treatments and their effects, then discusses a plan that can be followed consistently and reviewed if symptoms continue. A list of current medicines and previous treatments can guide the discussion..' WHERE `User` = 'drlim' AND CHAR_LENGTH(`WriteUp`) < 400;
UPDATE `doctor` SET `WriteUp` = 'Dr. Rao is a physiotherapist specialising in sports injuries, post-operative recovery and persistent back and neck pain. He builds progressive exercise plans around each patient’s goals, supporting a safe return to work, recreation and everyday movement. Assessment includes how pain affects activity, strength and mobility, so the plan addresses the tasks a patient wants to resume.\n\nPatients can book after an injury or operation, or when discomfort limits movement over time. Dr. Rao reviews progress with patients and adjusts exercises as strength and confidence improve. He provides guidance on pacing activity and practising movements between visits, with the aim of helping each person manage recovery as part of their normal routine. Patients can bring relevant reports and note which activities remain difficult..' WHERE `User` = 'drrao' AND CHAR_LENGTH(`WriteUp`) < 400;
